"""
Generate current_entities.txt: a snapshot of all canonical entity IDs and names
in the corpus. Pasted into the prompt at the start of every extraction session
so Claude can check for entity matches against the up-to-date corpus state.

Usage:
  python tools/entity_snapshot.py
  cat current_entities.txt    # then copy into the prompt
"""
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'current_entities.txt'

with open(OUT, 'w', encoding='utf-8') as out:
    out.write("Current corpus entities (auto-generated by tools/entity_snapshot.py).\n")
    out.write("Use this list to check for matches before minting new entities.\n")
    for folder in ['sources', 'persons', 'places', 'events']:
        out.write(f"\n=== {folder.upper()} ===\n")
        folder_path = ROOT / 'records' / folder
        if not folder_path.exists():
            continue
        for f in sorted(folder_path.glob('*.yaml')):
            with open(f, 'r', encoding='utf-8') as fp:
                docs = yaml.safe_load(fp)
            rec = docs[0] if isinstance(docs, list) else docs
            name = rec.get('standardised_name') or rec.get('standardised_title') or '?'
            out.write(f"  {rec.get('id')}  {name}\n")

print(f"Wrote {OUT.relative_to(ROOT)}")
